#ifndef WSCLEAN_VERSION_H
#define WSCLEAN_VERSION_H

#define WSCLEAN_VERSION_STR  "1.9b"
#define WSCLEAN_VERSION_MAJOR 1
#define WSCLEAN_VERSION_MINOR 9
#define WSCLEAN_VERSION_DATE "2015-09-17"

#endif
