#ifndef WSCLEAN_VERSION_H
#define WSCLEAN_VERSION_H

#define WSCLEAN_VERSION_STR  "1.12f"
#define WSCLEAN_VERSION_MAJOR 1
#define WSCLEAN_VERSION_MINOR 12
#define WSCLEAN_VERSION_DATE "2016-09-05"

#endif
